[build]
target = "thumbv6m-none-eabi"

[target.thumbv6m-none-eabi]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=--nmagic",
]

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort"]
